### ISSUE TITLE
Error after install QuickClose 5.0.13

### ISSUE THREAD

**Issue by technogenus** [reneeb/otrs-QuickClose#10]
After clean install of OTRS 5.0.18 and the QuickClose 5.0.13 package the QuickClose drop down is showing on tickets, but we cannot open the admin page.  The following PERL error is thrown:
[:error] Can't use an undefined value as a HASH reference at /opt/otrs//Kernel/Modules/AdminQuickClose.pm line 337.\n

*****
    my %DefaultNoteTypes = %{ $Self->{Config}->{ArticleTypes} };
    my %NoteTypes = $TicketObject->ArticleTypeList( Result => 'HASH' );
    for my $KeyNoteType ( keys %NoteTypes ) {
*****

**Comment by technogenus** [comment]
Changed code to show all articletype options, this works:

****
    my %NoteTypes = $TicketObject->ArticleTypeList( Result => 'HASH' );

    #for my $KeyNoteType ( keys %NoteTypes ) {
    #    if ( !$DefaultNoteTypes{ $NoteTypes{$KeyNoteType} } ) {
    #        delete $NoteTypes{$KeyNoteType};
    #    }
    #}
****

**Comment by reneeb** [comment]
Released as https://opar.perl-services.de/dist/QuickClose-5.0.14
